/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.achavez.farmaciaacg.src;

import com.achavez.farmaciaacg.dto.PedidoDTO;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author delph
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Pedidos
     */
    public Pedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdbGroupDistribuidor = new javax.swing.ButtonGroup();
        Background = new javax.swing.JPanel();
        lateralIzq = new javax.swing.JPanel();
        lbIcono = new javax.swing.JLabel();
        lbNombreFarmacia1 = new javax.swing.JLabel();
        lbNombreFarmacia2 = new javax.swing.JLabel();
        lbNombreFarmacia4 = new javax.swing.JLabel();
        btnHistorico = new javax.swing.JButton();
        lbTituloPanel = new javax.swing.JLabel();
        lbNombreMedicamento = new javax.swing.JLabel();
        lbTipoMedicamento = new javax.swing.JLabel();
        lbCantidadSolicitada = new javax.swing.JLabel();
        lbDistribuidor = new javax.swing.JLabel();
        lbSucursal = new javax.swing.JLabel();
        btnBorrar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        tfNombreMedicamento = new javax.swing.JTextField();
        cbxTipoMedicamento = new javax.swing.JComboBox<>();
        tfCantidadSolicitada = new javax.swing.JTextField();
        rdbCofarma = new javax.swing.JRadioButton();
        rdbEmpsephar = new javax.swing.JRadioButton();
        rdbCemefar = new javax.swing.JRadioButton();
        chbPrincipal = new javax.swing.JCheckBox();
        chbSecundaria = new javax.swing.JCheckBox();
        separador1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creación de pedidos farmacia ACG");
        setBackground(new java.awt.Color(44, 62, 80));
        setName("Principal"); // NOI18N
        setResizable(false);

        Background.setBackground(new java.awt.Color(44, 62, 80));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lateralIzq.setBackground(new java.awt.Color(86, 101, 115));

        lbIcono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbIcono.setIcon(new javax.swing.ImageIcon("D:\\Archivos\\Ingenieria de Software\\WSNetBeans\\farmaciaACG\\src\\main\\java\\com\\achavez\\farmaciaacg\\resources\\images\\icon.png")); // NOI18N
        lbIcono.setMaximumSize(new java.awt.Dimension(50, 50));

        lbNombreFarmacia1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbNombreFarmacia1.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreFarmacia1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreFarmacia1.setText("Farmacia");
        lbNombreFarmacia1.setToolTipText("");

        lbNombreFarmacia2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbNombreFarmacia2.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreFarmacia2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreFarmacia2.setText("Chávez");
        lbNombreFarmacia2.setToolTipText("");

        lbNombreFarmacia4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbNombreFarmacia4.setForeground(new java.awt.Color(255, 255, 255));
        lbNombreFarmacia4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNombreFarmacia4.setText("Alexander");
        lbNombreFarmacia4.setToolTipText("");

        btnHistorico.setBackground(new java.awt.Color(204, 204, 0));
        btnHistorico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistorico.setText("Historico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lateralIzqLayout = new javax.swing.GroupLayout(lateralIzq);
        lateralIzq.setLayout(lateralIzqLayout);
        lateralIzqLayout.setHorizontalGroup(
            lateralIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lateralIzqLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbNombreFarmacia1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbNombreFarmacia2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(lateralIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNombreFarmacia4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(lateralIzqLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lateralIzqLayout.setVerticalGroup(
            lateralIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lateralIzqLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbIcono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbNombreFarmacia1)
                .addGap(8, 8, 8)
                .addComponent(lbNombreFarmacia4)
                .addGap(18, 18, 18)
                .addComponent(lbNombreFarmacia2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Background.add(lateralIzq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 450));

        lbTituloPanel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbTituloPanel.setForeground(new java.awt.Color(255, 255, 255));
        lbTituloPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloPanel.setText("PEDIDOS");
        lbTituloPanel.setToolTipText("");
        Background.add(lbTituloPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 700, -1));

        lbNombreMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNombreMedicamento.setForeground(new java.awt.Color(213, 216, 220));
        lbNombreMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNombreMedicamento.setText("Nombre del medicamento:");
        lbNombreMedicamento.setToolTipText("");
        Background.add(lbNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 210, -1));

        lbTipoMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTipoMedicamento.setForeground(new java.awt.Color(213, 216, 220));
        lbTipoMedicamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTipoMedicamento.setText("Tipo del medicamento:");
        lbTipoMedicamento.setToolTipText("");
        Background.add(lbTipoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 210, -1));

        lbCantidadSolicitada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCantidadSolicitada.setForeground(new java.awt.Color(213, 216, 220));
        lbCantidadSolicitada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbCantidadSolicitada.setText("Cantidad solicitada:");
        lbCantidadSolicitada.setToolTipText("");
        Background.add(lbCantidadSolicitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 210, -1));

        lbDistribuidor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbDistribuidor.setForeground(new java.awt.Color(213, 216, 220));
        lbDistribuidor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbDistribuidor.setText("Distribuidor:");
        lbDistribuidor.setToolTipText("");
        Background.add(lbDistribuidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 210, -1));

        lbSucursal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbSucursal.setForeground(new java.awt.Color(213, 216, 220));
        lbSucursal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbSucursal.setText("Sucursal que solicita:");
        lbSucursal.setToolTipText("");
        Background.add(lbSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 210, -1));

        btnBorrar.setBackground(new java.awt.Color(79, 43, 43));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 37, 2));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        Background.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 130, 40));

        btnConfirmar.setBackground(new java.awt.Color(43, 79, 43));
        btnConfirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });
        Background.add(btnConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 320, 130, 40));

        tfNombreMedicamento.setBackground(new java.awt.Color(171, 178, 185));
        tfNombreMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfNombreMedicamento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfNombreMedicamento.setToolTipText("Nombre del medicamento");
        Background.add(tfNombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 440, 30));

        cbxTipoMedicamento.setBackground(new java.awt.Color(171, 178, 185));
        cbxTipoMedicamento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxTipoMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccione --", "analgésico", "analéptico", "anestésico", "antiácido", "antidepresivo", "antibióticos" }));
        cbxTipoMedicamento.setPreferredSize(new java.awt.Dimension(64, 23));
        Background.add(cbxTipoMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 440, 30));

        tfCantidadSolicitada.setBackground(new java.awt.Color(171, 178, 185));
        tfCantidadSolicitada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfCantidadSolicitada.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfCantidadSolicitada.setToolTipText("Nombre del medicamento");
        tfCantidadSolicitada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCantidadSolicitadaKeyTyped(evt);
            }
        });
        Background.add(tfCantidadSolicitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 440, 30));

        rdbCofarma.setBackground(new java.awt.Color(44, 62, 80));
        rdbGroupDistribuidor.add(rdbCofarma);
        rdbCofarma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbCofarma.setForeground(new java.awt.Color(213, 216, 220));
        rdbCofarma.setText("Cofarma");
        rdbCofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCofarmaActionPerformed(evt);
            }
        });
        Background.add(rdbCofarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        rdbEmpsephar.setBackground(new java.awt.Color(44, 62, 80));
        rdbGroupDistribuidor.add(rdbEmpsephar);
        rdbEmpsephar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbEmpsephar.setForeground(new java.awt.Color(213, 216, 220));
        rdbEmpsephar.setText("Empsephar ");
        rdbEmpsephar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEmpsepharActionPerformed(evt);
            }
        });
        Background.add(rdbEmpsephar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

        rdbCemefar.setBackground(new java.awt.Color(44, 62, 80));
        rdbGroupDistribuidor.add(rdbCemefar);
        rdbCemefar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdbCemefar.setForeground(new java.awt.Color(213, 216, 220));
        rdbCemefar.setText("Cemefar");
        rdbCemefar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbCemefarActionPerformed(evt);
            }
        });
        Background.add(rdbCemefar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        chbPrincipal.setBackground(new java.awt.Color(44, 62, 80));
        chbPrincipal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbPrincipal.setForeground(new java.awt.Color(242, 242, 242));
        chbPrincipal.setText("Principal");
        chbPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbPrincipalActionPerformed(evt);
            }
        });
        Background.add(chbPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        chbSecundaria.setBackground(new java.awt.Color(44, 62, 80));
        chbSecundaria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbSecundaria.setForeground(new java.awt.Color(242, 242, 242));
        chbSecundaria.setText("Secundaria");
        chbSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbSecundariaActionPerformed(evt);
            }
        });
        Background.add(chbSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 280, -1, -1));
        Background.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 440, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int opcion = JOptionPane.showOptionDialog(null, "¿Desea limpiar el formulario?", "Limpiar formulario", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, new Object[] { "Cancelar", "Aceptar"}, "Cancelar");
        if(opcion == 1){
            tfNombreMedicamento.setText("");
            cbxTipoMedicamento.setSelectedIndex(-1);
            tfCantidadSolicitada.setText("");
            rdbGroupDistribuidor.clearSelection();
            chbPrincipal.setSelected(false);
            chbSecundaria.setSelected(false);                    
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        PedidoDTO pedido = new PedidoDTO();
        pedido.setNombreMedicamento(tfNombreMedicamento.getText());
        pedido.setTipoMedicamento((cbxTipoMedicamento.getSelectedItem() != null) ? cbxTipoMedicamento.getSelectedItem().toString() : null);
        pedido.setCantidadMedicamento(tfCantidadSolicitada.getText());
        if(rdbCemefar.isSelected()){
            pedido.setDistribuidor("Cemefar");
        } else if(rdbCofarma.isSelected()){
            pedido.setDistribuidor("Cofarma");
        } else if(rdbEmpsephar.isSelected()){
            pedido.setDistribuidor("Empsephar");
        }
        
        if(chbPrincipal.isSelected()){
            pedido.setSucursalPrincipal("Calle de la Rosa n. 28");
        }
        
        if(chbSecundaria.isSelected()){
            pedido.setSucursalSecundaria("Calle Alcazabilla n. 3");
        }
        
        ValidaPedido validador = new ValidaPedido();
        if(validador.validarPedido(pedido)){
            Resumen resumenPedido = new Resumen();
            resumenPedido.setPedido(pedido);
            resumenPedido.setVisible(true);
            clearForm();
        }        
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void rdbCemefarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCemefarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCemefarActionPerformed

    private void rdbCofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbCofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbCofarmaActionPerformed

    private void rdbEmpsepharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEmpsepharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEmpsepharActionPerformed

    private void chbPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbPrincipalActionPerformed

    private void chbSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbSecundariaActionPerformed

    private void tfCantidadSolicitadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCantidadSolicitadaKeyTyped
        char tecla = evt.getKeyChar();
        if(!Character.isDigit(tecla)){
            evt.consume();
        }
    }//GEN-LAST:event_tfCantidadSolicitadaKeyTyped

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        // TODO add your handling code here:
        ListaPedidos lPedidos = new ListaPedidos();
        lPedidos.setVisible(true);
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void clearForm(){
        tfNombreMedicamento.setText("");
        cbxTipoMedicamento.setSelectedIndex(-1);
        tfCantidadSolicitada.setText("");
        rdbGroupDistribuidor.clearSelection();
        chbPrincipal.setSelected(false);
        chbSecundaria.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JComboBox<String> cbxTipoMedicamento;
    private javax.swing.JCheckBox chbPrincipal;
    private javax.swing.JCheckBox chbSecundaria;
    private javax.swing.JPanel lateralIzq;
    private javax.swing.JLabel lbCantidadSolicitada;
    private javax.swing.JLabel lbDistribuidor;
    private javax.swing.JLabel lbIcono;
    private javax.swing.JLabel lbNombreFarmacia1;
    private javax.swing.JLabel lbNombreFarmacia2;
    private javax.swing.JLabel lbNombreFarmacia4;
    private javax.swing.JLabel lbNombreMedicamento;
    private javax.swing.JLabel lbSucursal;
    private javax.swing.JLabel lbTipoMedicamento;
    private javax.swing.JLabel lbTituloPanel;
    private javax.swing.JRadioButton rdbCemefar;
    private javax.swing.JRadioButton rdbCofarma;
    private javax.swing.JRadioButton rdbEmpsephar;
    private javax.swing.ButtonGroup rdbGroupDistribuidor;
    private javax.swing.JSeparator separador1;
    private javax.swing.JTextField tfCantidadSolicitada;
    private javax.swing.JTextField tfNombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
